import "@/styles/globals.css";

import { cn } from "@/lib/utils";
import { Metadata } from "next";
import { ReactNode } from "react";
import { Toaster } from 'sonner'

import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head />
      <body className={cn("min-h-screen w-full font-sans antialiased")}>
        {children}
        <Toaster />
      </body>
    </html>
  );
}
